version: "3"
services: 
  jattach:
    image: dalognrong/jattach:openjdk-8
    build: 
      context: jattach
      dockerfile: Dockerfile
  jattach-11:
    image: dalognrong/jattach:openjdk-11
    build: 
      context: jattach
      dockerfile: Dockerfile-11
  async-profiler:
    image: dalognrong/async-profiler:openjdk-8
    build: 
      context: async-profiler
      dockerfile: Dockerfile
  async-profiler-11:
    image: dalognrong/async-profiler:openjdk-11
    build: 
      context: async-profiler
      dockerfile: Dockerfile-11